name: Run Tests

on:
  workflow_call:
    inputs:
      pkgname:
        required: true
        type: string
      install_string:
        required: True
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      ##############################################
      # Skip caching if using a local runner.
      - uses: actions/setup-python@v4
        if: ${{ !env.ACT }}
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: "pyproject.toml"
      - uses: actions/setup-python@v4
        if: ${{ env.ACT }}
        with:
          python-version: '3.10'
      ##############################################

      - name: Install package
        run: pip install "${{ inputs.install_string }}"

      - name: Code Quality
        run: python -m black ${{ inputs.pkgname }} tests/ --check

      - name: MyPy Typechecking
        run: python -m mypy ${{ inputs.pkgname }} tests/

      # Run tests.
      - name: Test with pytest
        run: python -m pytest
